server:
  port: 8083

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin1234@localhost:27018/decp_posts?authSource=admin}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  region: ${AWS_REGION:ap-south-1}
  s3:
    bucket-name: ${S3_BUCKET_NAME:decp-media-local}
