package com.decp.research.model;

public enum ResearchTag {
    MACHINE_LEARNING,
    DEEP_LEARNING,
    NLP,
    COMPUTER_VISION,
    CYBERSECURITY,
    CLOUD_COMPUTING,
    BLOCKCHAIN,
    IOT,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATABASES,
    SYSTEMS_PROGRAMMING,
    ALGORITHMS,
    DATA_SCIENCE,
    BIOINFORMATICS,
    QUANTUM_COMPUTING,
    OTHER
}
